name: Automated Linting
on:
  workflow_call:
    secrets:
      BOT_REPO_SCOPED_TOKEN:
        required: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - run: pnpm i --ignore-scripts
      - run: pnpm run lint
        name: Running linter
        id: eslint
        # There are currently many linting errors in sites-components.
        # This is a temporary fix to allow the workflow continue 
        # while these errors are being addressed.
        continue-on-error: true   
      - run: pnpm run prettier
        name: Running prettier
      - name: Push changes
        id: push-changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated linting/prettier update"
          add: "*"
          push: true
          pull: --rebase --autostash
          default_author: github_actions
      - name: Fail job if push changes
        if: steps.push-changes.outputs.pushed == 'true'
        run: echo "Linting/Prettier changes were made. Changes pushed."; exit 1;
      - name: Fail job on linting error
        if: steps.eslint.outcome == 'failure'
        run: echo "The linter found errors that must be manually addressed. See step, Running linter"; exit 1;