name: Automated Linting
on:
  workflow_call:
    secrets:
      BOT_REPO_SCOPED_TOKEN:
        required: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - run: pnpm i --ignore-scripts
      - run: pnpm run lint
        id: lint
        continue-on-error: true   
      - run: echo ${{ steps.lint.outcome }}   
      - run: pnpm run prettier
      - name: Automated Linting
        id: automated-linting
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated linting update"
          add: "*"
          push: true
          pull: --rebase --autostash
          default_author: github_actions
      - name: Fail job if push changes
        if: steps.automated-linting.outputs.pushed == 'true'
        run: exit 1;
      - name: Fail on linting error
        if: steps.lint.outcome == 'failure'
        run: exit 1;