name: Build and Test (Sites-Components)

on: push

jobs:
  call_build:
    uses: ./.github/workflows/build.yml
    with:
      package: "pages-components"

  call_unit_test:
    needs: call_build
    uses: ./.github/workflows/unit_test.yml
    with:
      package: "pages-components"